{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "0f59d953-d144-4e4d-a952-a52b827d6b28-attachment.txt", "type": "text/plain"}], "start": 1673067608791, "stop": 1673067610163, "uuid": "0a812f2e-b749-4399-adb5-804d98b41117", "historyId": "cea389e70229829d7b7acaa9728ffabb", "testCaseId": "b82774e9c2ae30ae4d6a970d043291d3", "fullName": "test.test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "11424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_test"}]}