{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "cde1b666-12d0-4f1b-b9e2-054ca8a47e66-attachment.txt", "type": "text/plain"}], "start": 1673064768696, "stop": 1673064770115, "uuid": "03abced2-f5ba-4ac1-bd5c-99627364b8c2", "historyId": "cea389e70229829d7b7acaa9728ffabb", "testCaseId": "b82774e9c2ae30ae4d6a970d043291d3", "fullName": "test.test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "1508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_test"}]}