{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "start": 1673413847446, "stop": 1673413859555, "uuid": "dfe0ffd1-a754-404b-b65b-024fd286ff15", "historyId": "7476709970f2f1cf914654527a445a30", "testCaseId": "4fec13cf75f39efea315e3ac5fcc40b7", "fullName": "test.test_login#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "9728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login"}]}