{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "b091f479-1eb5-4b06-a87e-858312352bc8-attachment.txt", "type": "text/plain"}], "start": 1673062281115, "stop": 1673062282436, "uuid": "c5de450f-d7ea-4c68-9229-7733af301b62", "historyId": "cea389e70229829d7b7acaa9728ffabb", "testCaseId": "b82774e9c2ae30ae4d6a970d043291d3", "fullName": "test.test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "regrassion"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "13484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_test"}]}