{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "62d46367-ba50-47d4-9dc5-a5bf047cd010-attachment.txt", "type": "text/plain"}], "start": 1673071797241, "stop": 1673071798627, "uuid": "06287a15-97d1-4016-bf66-99e0e4cb6862", "historyId": "cea389e70229829d7b7acaa9728ffabb", "testCaseId": "b82774e9c2ae30ae4d6a970d043291d3", "fullName": "test.test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "18800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_test"}]}