{"name": "test_login_verify_error_message_for_invalid_credential", "status": "passed", "attachments": [{"name": "stdout", "source": "8b9c89e0-93f1-4eee-87bb-024e145bd084-attachment.txt", "type": "text/plain"}], "start": 1673413891983, "stop": 1673413893380, "uuid": "18fe9fea-3b66-4639-bd2d-d789436d8f36", "historyId": "cea389e70229829d7b7acaa9728ffabb", "testCaseId": "b82774e9c2ae30ae4d6a970d043291d3", "fullName": "test.test_login_test.TestLogin#test_login_verify_error_message_for_invalid_credential", "labels": [{"name": "tag", "value": "regrassion"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-VH7USLGN"}, {"name": "thread", "value": "9728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_test"}]}